CREATE DATABASE IF NOT EXISTS cadastro_java;
USE cadastro_java;

CREATE TABLE IF NOT EXISTS cliente (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    estuda_etec VARCHAR(3) NOT NULL,
    estuda_outra_etec VARCHAR(3) NOT NULL,
    terminou_ensmedio VARCHAR(3) NOT NULL,
    escola VARCHAR(150) NOT NULL,
    cpf CHAR(150) NOT NULL,
    genero VARCHAR(150) NOT NULL,
    data_nasc CHAR(150) NOT NULL,
    nascimento VARCHAR(150) NOT NULL,
    filiacao_1 VARCHAR(150) NOT NULL,
    filiacao_2 VARCHAR(150) NOT NULL,
    habitacao VARCHAR(150) NOT NULL,
    afrodescendente VARCHAR(150) NOT NULL,
    escol_public CHAR(101) NOT NULL,
    local_nasc VARCHAR(150) NOT NULL,
    pais_origem VARCHAR(150) NOT NULL,
    rua_avenida VARCHAR(150) NOT NULL,
    complemento VARCHAR(150) NOT NULL,
    apt CHAR(100) NOT NULL,
    bloco CHAR(100) NOT NULL,
    bairro VARCHAR(150) NOT NULL,
    cidade VARCHAR(150) NOT NULL,
    cep CHAR(150) NOT NULL,
    telefone CHAR(150) NOT NULL,
    tlf_celular CHAR(150) NOT NULL,
    assitatura_pai VARCHAR(150) NOT NULL,
    responsavel_legal VARCHAR(150) NOT NULL,
    grau_parentesco CHAR(150) NOT NULL,
    serie_modulo CHAR(150) NOT NULL,
    periodo VARCHAR(150) NOT NULL,
);